# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-19 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0006_view_and_view_method_nullable'),
        ('rest_framework_tracking', '0006_auto_20180315_1442'),
    ]

    operations = [
    ]
