# -*- coding: utf-8 -*-
# Generated by Django 2.0.3 on 2018-04-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0006_auto_20180315_1442'),
        ('rest_framework_tracking', '0006_view_and_view_method_nullable'),
    ]

    operations = [
    ]
