# -*- coding: utf-8 -*-
# Generated by Django 3.0.2 on 2020-02-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0007_merge_20180419_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='username_persistent',
            field=models.CharField(
                blank=True,
                default='',
                max_length=200,
                null=True
            )
        ),
    ]
